SRC = src/Brain.cpp src/WrongAnimal.cpp src/WrongCat.cpp src/Animal.cpp src/Dog.cpp src/Cat.cpp src/main.cpp src/AAnimal.cpp
OBJ = $(SRC:.cpp=.o)
CC = g++
RM = rm -f
CPPFLAGS = -Wall -Wextra -Werror -std=c++98

NAME = AbstractClass

all: $(NAME)

$(NAME): $(OBJ)
	$(CC) $(CPPFLAGS) $(OBJ) -o $(NAME)

clean:
	$(RM) $(OBJ)

fclean: clean
	$(RM) $(NAME)

re: fclean $(NAME)

.PHONY: all clean fclean re